WebApplication2/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Comment
    {
        private string userName { get; set; }
        private string userEmail { get; set; }
        private string comment {get; set;}

        public Comment(string userName, string userEmail, string comment)
        {
            this.userName = userName;
            this.userEmail = userEmail;
            this.comment = comment;
        }

        public string getUserName()
        { return this.userName; }

        public string getUserEmail()
        { return this.userEmail; }

        public string getComment()
        { return this.comment; }
    }
}

WebApplication2/Models/Crud.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace WebApplication2.Models
{
    public class Crud
    {
        private static string connectionParams = @"Data Source = .\SQLEXPRESS;
                                        Initial Catalog = training;
                                        Integrated Security = False;
                                        User Id = root;
                                        Password = toor";

        public static List<Product> read()
        {
            List<Product> products = new List<Product>();
            string query = "SELECT* FROM products";

            using (SqlConnection connection = new SqlConnection(connectionParams))
            {
                try
                {
                    connection.Open();
                    SqlCommand command = new SqlCommand(query, connection);
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        products.Add(new Product(Convert.ToInt32(reader[0]), 
                                                reader[1].ToString(), 
                                                reader[2].ToString(),
                                                Convert.ToDouble(reader[3]),
                                                reader[4].ToString()));
                    }
                }
                catch (SqlException e)
                {
                    Console.WriteLine(e.Message);
                }
            };
            return products;
        }
    }
}

WebApplication2/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Product
    {
        private int id;
        private string name;
        private string description;
        private double price;
        private string category;

        public Product(int id, string name, string description, double price, string category)
        {
            this.id = id;
            this.name = name;
            this.description = description;
            this.price = price;
            this.category = category;
        }
    }
}

WebApplication2/Models/WorkingWithComments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace WebApplication2.Models
{
    public static class WorkingWithComments
    {
        private static string connectionParams = @"Data Source = .\SQLEXPRESS;
                                        Initial Catalog = training;
                                        Integrated Security = False;
                                        User Id = root;
                                        Password = toor";

        public static List<Comment> readComments()
        {
            List<Comment> comments = new List<Comment>();
            using (SqlConnection connection = new SqlConnection(connectionParams))
            {
                string query = "SELECT* FROM comments";
                SqlCommand command = new SqlCommand(query, connection);
                try
                {
                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        comments.Add(new Comment(reader["userName"].ToString(),
                                                 reader["userEmail"].ToString(),
                                                 reader["comment"].ToString()));
                    }

                }
                catch (SqlException e)
                {
                    Console.WriteLine(e.Message);
                }
            };
            return comments;
        }

        public static int addComment(Comment comment)
        {
            using (SqlConnection connection = new SqlConnection(connectionParams))
            {
                string query = string.Format("INSERT INTO comments VALUES (@userName, @userEmail, @comment)");
                SqlCommand command = new SqlCommand(query, connection);
                try 
                {
                    connection.Open();
                    command.Parameters.AddWithValue("@userName", comment.getUserName());
                    command.Parameters.AddWithValue("@userEmail", comment.getUserEmail());
                    command.Parameters.AddWithValue("@comment", comment.getComment());
                    return command.ExecuteNonQuery();
                }
            catch (SqlException e)
                {
                    Console.WriteLine(e.Message);
                    return 0;
                }
            };
    }
    }
}

WebApplication2/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CommentsController : Controller
    {
        //
        // GET: /Comments/
        public ActionResult Index()
        {
            return View(WorkingWithComments.readComments());
        }

        //
        // GET: /Comments/AddComment
        public ActionResult AddComment()
        {
            Comment comment = new Comment(Request.Form["userName"].ToString(), 
                                          Request.Form["userEmail"].ToString(), 
                                          Request.Form["comment"].ToString());
            return View(WorkingWithComments.addComment(comment));
        }
	}
}

WebApplication2/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security;

namespace WebApplication2.Controllers
{
    public class ContactsController : Controller
    {
        //
        // GET: /Contacts/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication2/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication2/Controllers/SkillsController.cs
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class SkillsController : Controller
    {
        // GET: Skills
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Views/Comments/AddComment.cshtml
@{
    ViewBag.Title = "AddComment";
}

@model int

@if (Model == 0)
{
    <h2>Комментарий не добавлен! Произошла досадная ошибка((</h2>
}
else
{
    <h2>Комментарий успешно добавлен!</h2>
    <input type="submit" value="Вернуться на главную страницу" class="btn" onclick="turnBack()"/>
}

WebApplication2/Views/Comments/Index.cshtml
@{
    ViewBag.Title = "Сообщения";
}

@model List<WebApplication2.Models.Comment>

<h2>Сообщения:</h2>
<div class="row">
    @{
        if (Model.Count == 0)
        {
            <h4>Сообщений пока нет.</h4>
        }
        else {
            foreach (var comment in Model)
            {
            <div class="col-lg-4">
                <h4>@comment.getUserName() (<i>@comment.getUserEmail()</i>)</h4>
                <label>@comment.getComment()</label>
                <hr />
            </div>
                }
            }
        }
</div>


<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <h2>Комментировать:</h2>
        @using (Html.BeginForm("AddComment", "Comments", FormMethod.Post, new { @role = "form" }))
        {
            <div class="form-group">
                <label>Ваше имя:</label>
                <input type="text" name="userName" class="form-control" placeholder="Имя" />
            </div>
            <div class="form-group">
                <label>Ваш email:</label>
                <input type="email" name="userEmail" class="form-control" placeholder="Email" />
            </div>
            <div class="form-group">
                <label>Ваш комментарий:</label>
                <textarea name="comment" class="form-control" ></textarea>
            </div>
            <div class="form-group col-lg-offset-3">
                <input type="submit" value="Оставить комментарий" class="btn btn-success"/>
            </div>
        }
    </div>
</div>

WebApplication2/Views/Contacts/Index.cshtml
@{
    ViewBag.Title = "Контакты";
}

<h2>Контакты</h2>

<div class="col-md-8">
    <p>
        Skype: gengod_original
    </p>
    <p>
        Телефон: +79511375515
    </p>
    <p>
        Личный сайт: <a href="gengod.esy.es">gengod.esy.es</a>
    </p>
    <p>
        Также можно написать мне <a href="comments/index">сообщение</a>
    </p>
    <input type="submit" class="btn" value="Вернуться на главную" onclick="turnBack()" />
</div>

WebApplication2/Views/Index/Index.cshtml
@{
    ViewBag.Title = "Сайт-визитка";
}

<style>
    .img-rounded {
        float: left;
        height: 320px;
        width: 240px;
    }
</style>

<div class="site-index">
    
    <div class="text-center">
        <h1>Добро пожаловать на мой сайт!</h1>
        <p class="lead">Данный сайт служит одной лишь цели - рассказать обо мне и моих навыках.</p>
    </div>
    <img class="img-rounded" sizes="320px" src="~/Content/Images/1jzrJ0wRST4.jpg">
    <div class="text-center">
        <p>Меня зовут Ветренко Богдан Юрьевич, я родился 24 декабря 1993 года.</p>
        <p>23 полных года.</p>
        <p>Проживаю в пригороде города Белгорода.</p>
        <p>С отличием окончил Харьковский Национальный университет имени В.Н. Каразина в 2016 году.</p>
        <p>Занимаюсь программированием 8 лет. За это время успел попробовать себя в системном, прикладном и веб-программировании.</p>
        <p>На данный момент ищу работу веб-программистом: Front-End developer, Back-End developer (PHP или ASP.NET)
           или Full-Stack developer (PHP или ASP.NET).</p>
        <p>Готов к переезду в любую точку нашей необъятной Родины!</p>
    </div>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Главная", "Index", "Index", null, new { @class = "navbar-brand" })
                    @Html.ActionLink("Мои навыки", "Index", "Skills", null, new { @class = "navbar-brand" })
                    @Html.ActionLink("Связаться со мной", "Index", "Contacts", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-right">
                    @Html.ActionLink("Войти на сайт", "Index", "LogIn", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody();
        </div>

        <script src="~/Scripts/jquery-3.1.1.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script>
            function turnBack() {
                document.location.href = "/Index/Index";
            }
        </script>
    </body>
</html>

WebApplication2/Views/Skills/Index.cshtml
@{
    ViewBag.Title = "Мои навыки";
}

<div class="body-content panel-primary">
    <div class="row">
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 1: C</i></h2>
            <p>
                Язык программирования С изучаается мной с 2010 года, знаю я его не досконально, но весьма неплохо. На языке С
                я создавал программные реализации криптографических протоколов (Шифры Цезаря, Вижинера, Биграммный шифр).
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 2: С++</i></h2>

            <p>
                На С++ я пишу с 2012 года. На нём написаны 2 моих курсовых (программная реализация ГОСТ 34.12-2015 "Кузнечик" и
                программная реализация алгоритмов сжатия информации методами Хаффмана и Шеннона-Фано) и дипломная работа
                (анализ и программная реализация алгоритма встраивания информации в кластерные файловые системы).
                Работаю с Visual C++ и Borland C++.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 3: C#</i></h2>

            <p>
                С# я начал изучать в 2014 году. Язык показался достаточно интересной альтернативой языку Java.
                На C# реализованы стеганографические алгоритмы группы LSB, приложение для генерации паролей с заданной сложностью
                и несколько небольших приложений под Windows 8.1, Windows Phone 8, UWP, Android (с использованием фреймворка
                Xamarin). Изучаю ASP.NET MVC 5, ADO.NET и LINQ.
                Могу написать работоспособные web-приложения с их помощью.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 4: Java</i></h2>

            <p>
                С Java я познакомился в 2013 году. С тех пор я изучил JDK 7, JDK 8, Java Collections Framework, а также JSP, Java Servlet,
                JDBC и Java Bean. На Java было написано множество лабораторных работ (в том числе, алгоритм арифметического кодирования
                информации и алгоритм генерации устойчивых к ошибкам кодов Хемминга), почти все из них были оценены на высший балл.
                Также, занимался программированием под ОС Android.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 5: PHP</i></h2>

            <p>
                Язык PHP изучаю с конца 2015 года. За это время я успел изучить PHP 5.6 и часть нововведений PHP 7. Освоил ООП
                в контексте данного языка. Умею реализовывать паттерн MVC, работать с базами данных используя класс PDO, знаком с
                шаблонизаторами, хэшированием и криптографией, реализованными средствами данного языка. Написание любого Back-End
                для меня не составит проблемы. Знаком с фреймворком Yii 2.0, с помощью которого, собственно, и написан данный сайт.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 6: JavaScript</i></h2>

            <p>
                JavaScript изучаю на протяжении трёх лет. За это время я успел изучить ООП в прототипном и функциональном стилях,
                работу с элементами DOM-дерева, технологию AJAX, фреймворк jQuery. В настоящее время нахожусь в процессе изучения
                фреймворка AngularJS.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 7: SQL</i></h2>

            <p>
                Работаю с SQL с университета. Умею писать сложные запросы. Работаю с MySQL версий 5.5+ и MS SQL Server 2012+.
                Могу работать с SQL
                средствами Java, C#, PHP.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 8: HTML</i></h2>

            <p>
                HTML занимаюсь около 3-х лет. За это время успел научиться быстрой вёрстке макетов и использовании HTML совместно
                с другиии языками. Знаю HTML 5. Умею делать кросс-браузерную вёрстку, резиновую вёрстку, осваиваю адаптивную вёрстку.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 9: CSS</i></h2>

            <p>
                CSS начал изучать примерно в одно время с HTML. Использую селекторы, псевдоклассы и нововведения CSS 3.
                Работаю с Bootstrap 3 и LESS.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 10: GIT</i></h2>

            <p>Работаю с GIT на протяжении более 4-х лет. Имею профиль на GitHub.</p>
        </div>
        <div class="col-md-4">
            <h2 class="text-success"><i>Навык 11: Linux</i></h2>

            <p>
                Достаточно давно знаком с ядром Linux. Работаю с его дистрибутивами на уровне пользователя, а также
                использую для разработки Front-End. Знаком с функциями коммандной строки и внутренним устройством ядра.
            </p>
        </div>
    </div>
</div>